{"name": "[Negative] Verify user can't login using non-exist username", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?", "trace": "browser_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5ec1a6e2cc9562e68f5393f8e7baf6b7\")>\n\n    @pytest.fixture(scope=\"session\")\n    def set_up(browser_driver):\n        \"\"\"Precondition.\"\"\"\n>       base_url = Login_page.login_url\nE       AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?\n\ntests\\test_login.py:31: AttributeError"}, "start": 1740990567624, "stop": 1740990567624, "uuid": "09ccd7cd-6e1d-4b68-a8f9-cfef9148deb0", "historyId": "42f9bad0da6b668bf1f97ba7126a78c1", "testCaseId": "42f9bad0da6b668bf1f97ba7126a78c1", "fullName": "tests.test_login#test_login_incorrect_username", "labels": [{"name": "story", "value": "User will failed login to website if credentials are incorrect"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "20884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}