{"name": "[Positive] Verify user can login on saucelabs using correct credentials", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?", "trace": "browser_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5ec1a6e2cc9562e68f5393f8e7baf6b7\")>\n\n    @pytest.fixture(scope=\"session\")\n    def set_up(browser_driver):\n        \"\"\"Precondition.\"\"\"\n>       base_url = Login_page.login_url\nE       AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?\n\ntests\\test_login.py:31: AttributeError"}, "start": 1740990567659, "stop": 1740990567659, "uuid": "92fd60a9-a799-4c12-9e58-201d36f393be", "historyId": "cfce530969d8b07c8d2d8c1371bdbbcd", "testCaseId": "cfce530969d8b07c8d2d8c1371bdbbcd", "fullName": "tests.test_login#test_login_correct_credentials", "labels": [{"name": "story", "value": "User can login to website using correct credentials"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "20884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}