{"name": "[Negative] Verify user can't login using non-exist username", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'", "trace": "set_up = <generator object set_up at 0x0000027883EE6190>\n\n    @step(\"user try login with non-existing usernmae\")\n    @story(\"User will failed login to website if credentials are incorrect\")\n    @title(\"[Negative] Verify user can't login using non-exist username\")\n    def test_login_incorrect_username(set_up):\n        driver = set_up\n        login_page = Login_page(driver)\n    \n        # Perform login with incorrect credentials\n>       login_page.login_as(\"std\", \"secret_sauce\")\n\ntests\\test_login.py:62: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\login_page.py:50: in login_as\n    self.insert_credentials(username, password)\npage\\login_page.py:45: in insert_credentials\n    self.insert_username(username)\npage\\login_page.py:25: in insert_username\n    self.action.double_click(self.get(self.username_col))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.login_page.Login_page object at 0x0000027883F3B830>, identfier = ('id', 'user-name')\n\n    def get(self, identfier:tuple) -> object:\n        \"\"\"Get element object by identifier\n    \n        Args:\n            identfier (tuple): For example, (By.ID, \"user-name\") or else.\n    \n        Returns:\n            object: Element object\n        \"\"\"\n>       return self.driver.find_element(*identfier)\nE       AttributeError: 'generator' object has no attribute 'find_element'\n\npage\\POM.py:77: AttributeError"}, "steps": [{"name": "user try login with non-existing usernmae", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\tests\\test_login.py\", line 62, in test_login_incorrect_username\n    login_page.login_as(\"std\", \"secret_sauce\")\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 50, in login_as\n    self.insert_credentials(username, password)\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 45, in insert_credentials\n    self.insert_username(username)\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Login as 'std' with password ''secret_sauce''", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 50, in login_as\n    self.insert_credentials(username, password)\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 45, in insert_credentials\n    self.insert_username(username)\n  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Insert username as 'std'", "status": "broken", "statusDetails": {"message": "AttributeError: 'generator' object has no attribute 'find_element'\n", "trace": "  File \"C:\\Users\\tan\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\test-package-xh99BTJe-py3.12\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\login_page.py\", line 25, in insert_username\n    self.action.double_click(self.get(self.username_col))\n                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\QA-practice\\Saucelabs\\python\\page\\POM.py\", line 77, in get\n    return self.driver.find_element(*identfier)\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "username", "value": "'std'"}], "start": 1740992155277, "stop": 1740992155278}], "parameters": [{"name": "username", "value": "'std'"}, {"name": "password", "value": "'secret_sauce'"}], "start": 1740992155277, "stop": 1740992155278}], "parameters": [{"name": "set_up", "value": "<generator object set_up at 0x0000027883EE6190>"}], "start": 1740992155277, "stop": 1740992155279}], "start": 1740992155277, "stop": 1740992155280, "uuid": "357c3dd5-44c7-4962-ac86-e98b71e97484", "historyId": "42f9bad0da6b668bf1f97ba7126a78c1", "testCaseId": "42f9bad0da6b668bf1f97ba7126a78c1", "fullName": "tests.test_login#test_login_incorrect_username", "labels": [{"name": "feature", "value": "Login"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "Validate Login Functionality"}, {"name": "story", "value": "User will failed login to website if credentials are incorrect"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "14380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}