{"name": "[Negative] Verify user can't login using wrong password", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?", "trace": "browser_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"5ec1a6e2cc9562e68f5393f8e7baf6b7\")>\n\n    @pytest.fixture(scope=\"session\")\n    def set_up(browser_driver):\n        \"\"\"Precondition.\"\"\"\n>       base_url = Login_page.login_url\nE       AttributeError: type object 'Login_page' has no attribute 'login_url'. Did you mean: 'login_as'?\n\ntests\\test_login.py:31: AttributeError"}, "start": 1740990565854, "stop": 1740990565854, "uuid": "909d00b4-cd7c-46c4-8c59-dd188dc8317c", "historyId": "ad387778e25dc5b6051a2dfd42784c1f", "testCaseId": "ad387778e25dc5b6051a2dfd42784c1f", "fullName": "tests.test_login#test_login_incorrect_password", "labels": [{"name": "story", "value": "User will failed login to website if credentials are incorrect"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "LOQ15"}, {"name": "thread", "value": "20884-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}